version: 1.0.{build}
image: Visual Studio 2017
platform:
- x86
- x64
clone_folder: C:\GOPATH\src\github.com\go-rillas\subprocess
environment:
  GOPATH: C:\GOPATH
install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
build_script:
- cmd: go get -v -d -t github.com/go-rillas/subprocess/...
- cmd: go get -u -v github.com/chrissimpkins/climock/...
test_script:
- cmd: go test -v ./...